--EN ÇOK SATIÞ YAPAN 3 KULLANICI
SELECT TOP 3 KULLANICIID, AD, SOYAD, SATISADET 
AS 'YAPTIÐI SATIÞ ADEDÝ' FROM KULLANICILAR ORDER BY SATISADET DESC

--EN ÇOK ÜRÜN ALAN 3 KULLANICI
SELECT TOP 3 KULLANICIID, AD, SOYAD, ALISADET 
AS 'ALDIÐI ÜRÜN ADEDÝ' FROM KULLANICILAR ORDER BY ALISADET DESC

--FÝYAT BAZLI EN ÇOK ÜRÜN ALAN KULLANICI
SELECT TOP 3 KULLANICIID, AD, SOYAD, ISLEMTOPLAMALIS 
AS 'ALDIÐI ÜRÜNLERÝN TOPLAMI' FROM KULLANICILAR ORDER BY ISLEMTOPLAMALIS DESC

--FÝYAT BAZLI EN ÇOK ÜRÜN SATAN KULLANICI
SELECT TOP 3 KULLANICIID, AD, SOYAD, ISLEMTOPLAMSATIS 
AS 'ALDIÐI ÜRÜNLERÝN TOPLAMI' FROM KULLANICILAR ORDER BY ISLEMTOPLAMSATIS DESC

--FÝYAT BAZLI EN ÇOK ÜRÜN SATAN KULLANICI
SELECT TOP 3 KULLANICIID, AD, SOYAD, ISLEMTOPLAMSATIS 
AS 'SATTIÐI ÜRÜNLERÝN TOPLAMI' FROM KULLANICILAR ORDER BY ISLEMTOPLAMSATIS DESC

--SATIÞTA OLAN ÜRÜNLERÝN FÝYATA GÖRE SIRALAMASI
SELECT BASLIK, ACIKLAMA,FIYAT 
FROM URUNLER 
WHERE DURUM = 'SATIÞTA' ORDER BY FIYAT DESC

--EN ÇOK TERCÝH BEÐENÝLEN URUN
SELECT URUNID,BASLIK, ACIKLAMA, FIYAT 
FROM URUNLER 
WHERE URUNID = (SELECT TOP 1 URUNID FROM FAVORILER
GROUP BY  URUNID ORDER BY COUNT(URUNID) DESC)


--HER KULLANICININ SATIÞTAKÝ ÜRÜNLERÝ
SELECT AD, SOYAD, ACIKLAMA, FIYAT 
FROM KULLANICILAR, URUNLER 
WHERE KULLANICILAR.KULLANICIID = URUNLER.SATICIID AND URUNLER.DURUM = 'SATIÞTA'

--HER BÝR KATEGORININ ALT KATEGORÝLERÝ
SELECT KATEGORITURU,  ALTKATEGORITURU 
FROM KATEGORI, ALTKATEGORI 
WHERE KATEGORI.KATEGORIID = ALTKATEGORI.KATEGORIID

--HER KULLANICININ BEÐENDÝÐÝ ÜRÜNLERÝN LÝSTESÝ
SELECT AD, SOYAD, BASLIK, ACIKLAMA 
FROM KULLANICILAR, URUNLER, FAVORILER 
WHERE KULLANICILAR.KULLANICIID = FAVORILER.KULLANICIID AND FAVORILER.URUNID = URUNLER.URUNID

--KULLANICILARIN KAYITLI OLDUÐU ADRESLERÝN LÝSTESÝ
SELECT AD, SOYAD, ADRES, ADRESACIKLAMA
FROM KULLANICILAR, ADRES
WHERE KULLANICILAR.KULLANICIID = ADRES.KULLANICIID 

--EN ÇOK KULLANILAN KARGO FÝRMALARI
SELECT FIRMAADI, COUNT(SATIS.KARGOID) FROM KARGO, SATIS WHERE SATIS.KARGOID = KARGO.KARGOID GROUP BY FIRMAADI 

--ÞATIÞ DURUMU BEKLEMEDE OLAN ÜRÜNLERÝN ÝÞLEMÝN NE KADAR SÜRDÜÐÜNÜN LÝSTESÝ
SELECT DATEDIFF(YEAR,ISLEMTARIHI,EKLEMETARIHI) AS 'GEÇEN SÜRE' , BASLIK, ACIKLAMA 
FROM URUNLER, SATIS 
WHERE URUNLER.URUNID = SATIS.URUNID  AND URUNLER.DURUM = 'BEKLEMEDE'

--ÜRÜNLERÝN NE KADAR SÜREDÝR SATIÞTA OLDUÐU
SELECT URUNID,BASLIK,ACIKLAMA, DATEDIFF(DAY,EKLEMETARIHI,GETDATE()) AS 'GÜNDÜR SATIÞTA'
FROM URUNLER

--EKLENMESÝNÝN ÜZERÝNDEN 30 GÜN GEÇEN ÜRÜNLER
SELECT URUNID,BASLIK,ACIKLAMA, DATEDIFF(DAY,EKLEMETARIHI,GETDATE()) AS 'GÜNDÜR SATIÞTA'
FROM URUNLER  WHERE DATEDIFF(DAY,EKLEMETARIHI,GETDATE()) > 30

--SATIÞTAKÝ ÜRÜNLERÝN GENEL BÝLGÝLERÝ
SELECT URUNID, BASLIK, ACIKLAMA, KATEGORITURU, ALTKATEGORITURU, MARKAADI, FIYAT, EKLEMETARIHI, CINSIYET, BEDEN 
FROM URUNLER, KATEGORI, ALTKATEGORI, MARKALAR
WHERE URUNLER.KATEGORIID = KATEGORI.KATEGORIID AND URUNLER.ALTKATEGORIID = ALTKATEGORI.ALTKATEGORIID AND URUNLER.MARKAID = MARKALAR.MARKAID
AND DURUM = 'SATIÞTA'
