CREATE TABLE KULLANICILAR(
KULLANICIID INT IDENTITY(1,1),
AD VARCHAR(30),
SOYAD VARCHAR(30),
EMAIL VARCHAR(30) NOT NULL UNIQUE,
KULLANICIADI VARCHAR(30) NOT NULL UNIQUE ,
SIFRE VARCHAR(30) NOT NULL,
KAYITTARIHI DATE NOT NULL DEFAULT(GETDATE()),
DOGUMTARIHI VARCHAR(11),
TELNO VARCHAR(30),
CINSIYET VARCHAR(10),
ISLEMTOPLAMSATIS INT DEFAULT 0,
ISLEMTOPLAMALIS INT DEFAULT 0,
ALISADET INT DEFAULT 0,
SATISADET INT DEFAULT 0,
PRIMARY KEY(KULLANICIID))

CREATE TABLE ADRES(
ADRESID INT IDENTITY(1,1),
KULLANICIID INT,
ADRES VARCHAR(30),
ADRESACIKLAMA VARCHAR(30),
PRIMARY KEY(ADRESID),
FOREIGN KEY (KULLANICIID) REFERENCES KULLANICILAR(KULLANICIID))

CREATE TABLE KATEGORI(
KATEGORIID INT IDENTITY(1,1),
KATEGORITURU VARCHAR(30),
PRIMARY KEY(KATEGORIID))


CREATE TABLE ALTKATEGORI(
ALTKATEGORIID INT IDENTITY(1,1),
ALTKATEGORITURU VARCHAR(30),
KATEGORIID INT,
PRIMARY KEY(ALTKATEGORIID),
FOREIGN KEY (KATEGORIID) REFERENCES KATEGORI(KATEGORIID))


CREATE TABLE MARKALAR(
MARKAID INT IDENTITY(1,1),
MARKAADI VARCHAR(30),
PRIMARY KEY(MARKAID))


CREATE TABLE URUNLER(
URUNID INT IDENTITY(1,1),
SATICIID INT,
BASLIK VARCHAR(50),
ACIKLAMA VARCHAR(50),
FIYAT INT,
EKLEMETARIHI DATE NOT NULL DEFAULT(GETDATE()),
DURUM VARCHAR(30) NOT NULL DEFAULT 'SATIÞTA',
KULLANIMDURUMU VARCHAR(30),
CINSIYET VARCHAR(10),
BEDEN VARCHAR(30),
MARKAID INT,
KATEGORIID INT,
ALTKATEGORIID INT,
PRIMARY KEY(URUNID),
FOREIGN KEY (SATICIID) REFERENCES KULLANICILAR(KULLANICIID),
FOREIGN KEY (KATEGORIID) REFERENCES KATEGORI(KATEGORIID) ON DELETE SET NULL,
FOREIGN KEY (MARKAID) REFERENCES MARKALAR(MARKAID),
FOREIGN KEY (KATEGORIID) REFERENCES KATEGORI(KATEGORIID),
FOREIGN KEY (ALTKATEGORIID) REFERENCES ALTKATEGORI(ALTKATEGORIID))

CREATE TABLE FAVORILER(
FAVORIID INT IDENTITY(1,1),
URUNID INT,
KULLANICIID INT,
PRIMARY KEY(FAVORIID),
FOREIGN KEY (URUNID) REFERENCES URUNLER(URUNID) ON DELETE CASCADE,
FOREIGN KEY (KULLANICIID) REFERENCES KULLANICILAR(KULLANICIID))

CREATE TABLE KARGO(
KARGOID INT IDENTITY(1,1),
FIRMAADI VARCHAR(20),
PRIMARY KEY(KARGOID))


CREATE TABLE SATIS(
SATISID INT IDENTITY(1,1),
SATICIID INT,
ALICIID INT,
URUNID INT,
KARGOID INT,
ISLEMTARIHI DATE NOT NULL DEFAULT(GETDATE()),
DURUM VARCHAR(30) NOT NULL DEFAULT 'BEKLEMEDE',
PRIMARY KEY(SATISID),
FOREIGN KEY (SATICIID) REFERENCES KULLANICILAR(KULLANICIID),
FOREIGN KEY (ALICIID) REFERENCES KULLANICILAR(KULLANICIID),
FOREIGN KEY (KARGOID) REFERENCES KARGO(KARGOID),
FOREIGN KEY (URUNID) REFERENCES URUNLER(URUNID))

CREATE TRIGGER URUNDURUMUGUNCELLEME
ON SATIS AFTER INSERT
AS
BEGIN
DECLARE @ID INT 
SELECT @ID = URUNID FROM inserted
UPDATE URUNLER SET DURUM = 'BEKLEMEDE' WHERE URUNID = @ID
END


CREATE TRIGGER SATISTANKALDIRMA
ON SATIS AFTER UPDATE
AS
BEGIN
IF(UPDATE(DURUM))
BEGIN
DECLARE @ID INT
SELECT @ID = URUNID FROM deleted
UPDATE URUNLER SET DURUM = 'SATILDI' WHERE URUNID = @ID
END
END


CREATE TRIGGER IADEDURUMU
ON SATIS AFTER DELETE
AS
BEGIN
DECLARE @ID INT
SELECT @ID = URUNID FROM deleted
UPDATE URUNLER SET DURUM = 'SATIÞTA' WHERE URUNID = @ID
END

CREATE TRIGGER FIYATKONTROL
ON URUNLER AFTER INSERT
AS
BEGIN
DECLARE @ID INT 
DECLARE @FIYAT INT 
SELECT @ID = URUNID, @FIYAT = FIYAT FROM inserted
IF(@FIYAT > 1300)
BEGIN
PRINT 'GÝRDÝÐÝNÝZ FÝYAT DEÐERÝ LÝMÝTÝN ÜSTÜNDE LÜTFEN 100000 DEN AZ DEÐER GÝRÝNÝZ'
DELETE FROM URUNLER WHERE URUNID = @ID
END
END

CREATE TRIGGER ISLEMEKLEME
ON SATIS AFTER INSERT
AS
BEGIN
DECLARE @SATICIID INT
DECLARE @ALICIID INT
DECLARE @URUNID INT
DECLARE @FIYAT INT
DECLARE @GUNCELFIYATSATIS INT
DECLARE @GUNCELFIYATALIS INT
DECLARE @SATISADET INT
DECLARE @ALISADET INT
SELECT @ALICIID = ALICIID, @SATICIID = SATICIID, @URUNID = URUNID FROM inserted
SELECT @FIYAT = FIYAT FROM URUNLER WHERE URUNID = @URUNID
SELECT @GUNCELFIYATALIS =  ISLEMTOPLAMALIS FROM KULLANICILAR WHERE KULLANICIID = @ALICIID
SELECT @SATISADET =  SATISADET FROM KULLANICILAR WHERE KULLANICIID = @SATICIID
SELECT @ALISADET =  ALISADET FROM KULLANICILAR WHERE KULLANICIID = @ALICIID
SELECT @GUNCELFIYATSATIS =  ISLEMTOPLAMSATIS FROM KULLANICILAR WHERE KULLANICIID = @SATICIID
UPDATE KULLANICILAR SET ISLEMTOPLAMALIS = @GUNCELFIYATALIS + @FIYAT, ALISADET = @ALISADET + 1 WHERE KULLANICIID = @ALICIID
UPDATE KULLANICILAR SET ISLEMTOPLAMSATIS = @GUNCELFIYATSATIS + @FIYAT, SATISADET = @SATISADET + 1 WHERE KULLANICIID = @SATICIID
END
